const TERMS = [
  "Zahnspange", "Huepfburg", "Korkenzieher", "Nikolausstiefel", "Schnorchel",
  "Blinddarm", "Liftschacht", "Fischstaebchen", "Vokuhila", "Maibaum",
  "Kartoffelsalat", "Treibhaus", "Stethoskop", "Haengematte", "Kaktus",
  "Dartscheibe", "Wasserrutsche", "Trampolin", "Regenschirm", "Rolltreppe",
  "Briefkasten", "Staudamm", "Iglu", "Windmuehle", "Zirkuszelt",
  "Feuerwehrleiter", "Baumhaus", "Leuchtturm", "Wasserpumpe", "Reissverschluss",
  "Taucherbrille", "Sandburg", "Thermometer", "Schornstein", "Waescheleine",
  "Badewanne", "Zitronenpresse", "Waffeleisen", "Suppenkelle", "Flaschnoeffner",
  "Nudelholz", "Eierschneider", "Salatschleuder", "Spargel", "Artischocke",
  "Kohlrabi", "Rosenkohl", "Fenchel", "Rhabarber", "Maiskolben",
  "Zuckerwatte", "Lebkuchenhaus", "Brezel", "Baumstumpf", "Vogelscheuche",
  "Weinrebe", "Heuballen", "Komposthaufen", "Bienenstock", "Spinnennetz",
  "Hasenstall", "Huehnerstall", "Schubkarre", "Giesskanne", "Rasenmaeher",
  "Heckenschere", "Spaten", "Harke", "Schnecke", "Regenwurm",
  "Marienkaefer", "Libelle", "Tausendfuessler", "Skorpion", "Tarantel",
  "Straussennei", "Schildkroete", "Leguan", "Kobra", "Krokodil",
  "Nilpferd", "Zebra", "Nashorn", "Gorilla", "Faultier",
  "Guerteltier", "Stachelschwein", "Erdmaennchen", "Flamingo", "Pelikan",
  "Tukan", "Papagei", "Pfauenfeder", "Albatros", "Moewe",
  "Reiher", "Storch", "Kranich", "Adler", "Uhu",
  "Fledermaus", "Igel", "Eichhoernchen", "Murmeltier", "Biber",
  "Waschbaer", "Fuchs", "Dachs", "Rentier", "Elch",
  "Wildschwein", "Gluehbirne", "Steckdose", "Verlaengerungskabel", "Taschenlampe",
  "Kronleuchter", "Lampenschirm", "Lokomotive", "Heissluftballon", "Zeppelin",
  "Hubschrauber", "Gleitschirm", "Fallschirm", "Rakete", "Raumanzug",
  "Teleskop", "Fernrohr", "Mikroskop", "Sanduhr", "Sonnenuhr",
  "Kuckucksuhr", "Metronom", "Stimmgabel", "Xylofon", "Trommel",
  "Kastagnetten", "Tamburin", "Akkordeon", "Dudelsack", "Panfloete",
  "Kazoo", "Mundharmonika", "Banjo", "Harfe", "Fagott",
  "Klarinette", "Saxofon", "Posaune", "Tuba", "Alphorn",
  "Blockfloete", "Kirchenglocke", "Maracas", "Bongo", "Djembe",
  "Plattenspieler", "Ghettoblaster", "Flipperautomat", "Tischkicker", "Tischtennisplatte",
  "Billardtisch", "Bowlingkugel", "Schachfigur", "Domino", "Jenga",
  "Kreisel", "Bumerang", "Jo-Jo", "Diabolo", "Hula-Hoop",
  "Springseil", "Skateboard", "Einrad", "Dreirad", "Kettcar",
  "Rutschbahn", "Sandkasten", "Schaukel", "Wippe", "Klettergeruest",
  "Drachen", "Seifenblase", "Wasserpistole", "Modelleisenbahn", "Puppenhaus",
  "Schaukelpferd", "Hampelmann", "Marionette", "Bauklotze", "Puzzlestueck"
];

export default TERMS;
